#!/bin/bash
[ -z $1 ] && printf "\033[1;33mUsage:\033[m\033[0;32m ./CPU_monitor \033[2m<process-name>\033[m\n" && exit
check=1
while true; do
  output=$(ps -Ao comm,pcpu | grep $1)
  if [ ! -z "$output" ]; then
    printf "\033[2;3;6;35m(check: $check)\033[m\n"
    printf "\033[1;36mPROGRAM\033[m  |  \033[1;33mCPU usage\033[m\n"
    printf "\033[3;6;34m"
    echo "$output%"
    printf "\033[m"
    ((++check))
  fi  
  sleep 1.87
done

